steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/palomade-test:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/palomade-test:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "palomade-test"
      - "--image=gcr.io/$PROJECT_ID/palomade-test:$COMMIT_SHA"
      - "--region=us-central1"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=DB_HOST=db_host:latest,DB_USER=db_username:latest,DB_PASSWORD=db_password:latest,SECRET_KEY=palomade_secret_key:latest,HASH_KEY=palomade_hash_key:latest,MAIL_HOST=palomade_mail_host:latest,MAIL_PORT=palomade_mail_port:latest,MAIL_USER=palomade_mail_user:latest,MAIL_PASSWORD=palomade_mail_password:latest"
images:
  - "gcr.io/$PROJECT_ID/palomade-test:$COMMIT_SHA"
logsBucket: "gs://palomade-test-buckets/logs"
